workflows:
  ios-cocoapods-test:
    name: iOS CocoaPods Sandbox
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcodeproj"
        XCODE_SCHEME: "App"
      xcode: latest

    scripts:
      - name: Use Bundler to install CocoaPods
        script: |
          bundle install
          bundle exec pod install --verbose

      - name: Optional build step
        script: |
          xcodebuild -project "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/**/*
