workflows:
  ios-cocoapods-test:
    name: iOS CocoaPods Sandbox
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcodeproj"
        XCODE_SCHEME: "App"
      xcode: latest
      ruby: 3.1.4  # ✅ Downgrade from Ruby 3.3.6 to avoid CocoaPods path errors

    scripts:
      - name: Downgrade CocoaPods to 1.15.2
        script: |
          gem uninstall cocoapods --all --executables
          gem install cocoapods -v 1.15.2

      - name: Install dependencies with pod install
        script: |
          pod install --verbose

      - name: Optional build step
        script: |
          xcodebuild -project "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/**/*
